deployment:
  tasks:
    - export DEPLOYPATH=/home3/blueceko/stellalifesciences.com
    - export REPOPATH=/home3/blueceko/repositories/stellalifesciences.com
    # Go to repository folder
    - cd $REPOPATH
    # Install dependencies
    - npm install
    # Build Next.js for production
    - npm run build
    # Copy .next and static files to deployment path
    - rsync -a --delete .next public package.json $DEPLOYPATH
