deployment:
  tasks:
    # Set paths
    - export DEPLOYPATH=/home3/blueceko/stellalifesciences.com
    - export REPOPATH=/home3/blueceko/repositories/stellalifesciences.com

    # Sync source code (so package.json, server.js, next.config.js exist in DEPLOYPATH)
    - rsync -a --delete $REPOPATH/ $DEPLOYPATH/

    # Go to deploy path and install dependencies
    - cd $DEPLOYPATH
    - npm install
    - npm run build
